Bindu | Changes required to merge to make CURE-Product-Master as dev branch (#21)
* Bindu | Changes required to merge make CURE-Product-Master as dev branch

* Bindu | Changes required to merge make CURE-Product-Master as dev branch

diff --git a/.github/workflows/build_publish.yml b/.github/workflows/build_publish.yml
--- a/.github/workflows/build_publish.yml
+++ b/.github/workflows/build_publish.yml
@@ -1,36 +1,87 @@
 name: Build and Publish package
 on:
   push:
-    branches: [ master ]
+    branches: [ CURE-Product-Master ]
   workflow_dispatch:
 
 jobs:
+  Trivy:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v3
+      - name: Trivy Scan
+        run: |
+          wget -q https://raw.githubusercontent.com/Bahmni/bahmni-infra-utils/main/trivy_scan.sh && chmod +x trivy_scan.sh
+          ./trivy_scan.sh
+          rm trivy_scan.sh
   build-publish-package:
     name: Build and Publish package
-    runs-on: macos-14
+    runs-on: ubuntu-latest
+    needs: Trivy
     steps:
       - uses: actions/checkout@v2
-      - name: Set up JDK 1.8
-        uses: actions/setup-java@v1
+      - name: Set up JDK 8
+        uses: actions/setup-java@v3
         with:
-          java-version: 1.8
-          server-id: nexus-sonatype
-          server-username: NEXUS_USERNAME
-          server-password: NEXUS_PASSWORD
-      - name: Cache Maven packages
-        uses: actions/cache@v3
-        with:
-          path: ~/.m2
-          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
-          restore-keys: ${{ runner.os }}-m2
-      - name: Build and deploy with Maven
+          distribution: temurin
+          java-version: '8'
+          cache: maven
+      - name: Configure Maven settings for GitHub Packages
         run: |
-          PROJECT_VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
-          if [[ "$PROJECT_VERSION" == *"-SNAPSHOT" ]]; then
-            ./mvnw --no-transfer-progress clean -U deploy
-          else
-            echo "❌ The current push is for release. So skipping build."
-          fi
+          mkdir -p ~/.m2
+          cat > ~/.m2/settings.xml <<EOF
+          <settings>
+            <servers>
+              <server>
+                <id>github</id>
+                <username>${{ github.actor }}</username>
+                <password>${{ secrets.CURE_EMR_ORG_ACCESS_TOKEN }}</password>
+              </server>
+            </servers>
+          </settings>
+          EOF
+      - name: Build and deploy with Maven
+        run: ./mvnw --no-transfer-progress clean -U deploy -DskipTests
+
+      - name: Delete Existing Release and Tag
         env:
-          NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
-          NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          release_name="Release-v2.0.0.ipd"
+          tag_name="v2.0.0.ipd"
+
+          # Fetch all releases and filter by release name to get the release ID
+          release_id=$(curl -s -X GET -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases" | jq -r --arg release_name "$release_name" '.[] | select(.name == $release_name) | .id')
+
+          if [ ! -z "$release_id" ] && [ "$release_id" != "null" ]; then
+            # Delete the release using the release ID
+            curl -s -X DELETE -H "Authorization: token $GITHUB_TOKEN" "https://api.github.com/repos/${{ github.repository }}/releases/$release_id"
+            echo "Deleted release $release_name"
+          else
+            echo "No release found for $release_name to delete."
+          fi
+
+          # Attempt to delete the tag on the remote repository
+          git push --delete origin $tag_name || echo "Tag $tag_name not found on remote."
+      - name: Create GitHub release
+        id: create_release
+        uses: actions/create-release@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          tag_name: v2.0.0.ipd
+          release_name: Release-v2.0.0.ipd
+          draft: false
+          prerelease: false
+
+      - name: Upload SNAPSHOT.omod to release
+        uses: actions/upload-release-asset@v1
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        with:
+          upload_url: ${{ steps.create_release.outputs.upload_url }}
+          asset_path: bahmnicore-omod/target/bahmnicore-omod-2.0.0.ipd-SNAPSHOT.omod
+          asset_name: bahmnicore-omod-2.0.0.ipd-SNAPSHOT.omod
+          asset_content_type: application/octet-stream
+
